version: '3.5'

services:
  traefik:
    container_name: traefik
    image: traefik:v2.5
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.contact-web.address=:8085"
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
      - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.http.http.redirections.entryPoint.priority=10" # disable permanent forwarding for every route
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${useremail}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.${HOSTNAME}`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
#      - "traefik.http.routers.api.tls.domains[0].main=api.${HOSTNAME}"
#      - "traefik.http.routers.api.tls.domains[0].sans=*.${HOSTNAME}"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=mywhitelist@docker"
      #      - "traefik.http.middlewares.mywhitelist.ipwhitelist.sourcerange=127.0.0.1/32, 0.0.0.0/0"
      - "traefik.http.middlewares.mywhitelist.ipwhitelist.sourcerange=127.0.0.1/32, 83.85.42.212"
    ports:
      - "80:80"
      - "443:443"
      - "8085:8085"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
