version: '3.5'

services:
  traefik:
    container_name: traefik
    image: traefik:v2.5
    env_file: docker-compose-no-ssl.env
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.contact-web.address=:8085"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8085:8085"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
