  [http.routers]
   # Define a connection between requests and services
     [http.routers.dataverse]
        rule = "Host(`portal.{{ env "hostname" }}`)"
        entrypoints = ["websecure"]
        service = "dataverse"
     [http.routers.dataverse.tls]
        certResolver = "myresolver"
     [http.routers.skosmos]
        rule = "Host(`skosmos.{{ env "hostname" }}`)"
        entrypoints = ["websecure"]
        service = "skosmos"
     [http.routers.skosmos.tls]
        certResolver = "myresolver"
     [http.routers.fuseki]
       rule = "Host(`fuseki.{{ env "hostname" }}`)"
       entrypoints = ["websecure"]
       service = "fuseki"
     [http.routers.fuseki.tls]
        certResolver = "myresolver"

 [http.services]
        # Define how to reach an existing service on our infrastructure
        [http.services.dataverse.loadBalancer]
           [[http.services.dataverse.loadBalancer.servers]]
             url = "http://dataverse:8080"
        [http.services.skosmos.loadBalancer]
           [[http.services.skosmos.loadBalancer.servers]]
             url = "http://skosmos:80"
        [http.services.fuseki.loadBalancer]
           [[http.services.fuseki.loadBalancer.servers]]
             url = "http://fuseki:3030"
